#!/bin/sh -e
# check we have a simulator tree
if [ ! -d ../simulator ] ; then
  echo "downloading aarch64 simulator code from sourceforge into directory ../simulator"
  (cd .. ; hg clone http://hg.code.sourceforge.net/p/smallaarch64sim/code simulator)
fi

if [ ! -d ../binutils ] ; then
  echo "downloading aarch64 binutils code from sourceforge into directory ../binutils"
  echo "by executing the following command"
  (cd .. ; hg clone http://hg.code.sourceforge.net/p/binutilsaarch64/code binutils)
fi

# ensure the sim lib has been built
if [ ! -f ../simulator/libarmsim.so ] ; then
  (cd ../simulator ; make)
fi

# ensure the hsdis lib has been built

if [ ! -f hotspot/src/share/tools/hsdis/build/linux-amd64/hsdis-amd64.so ] ; then
  (export BINUTILS=`cd .. ; pwd`/binutils ; cd hotspot/src/share/tools/hsdis ; make BUILD_AARCH64=true)
fi

make ALLOW_DOWNLOADS="true" ALT_JDK_IMPORT_PATH=/usr/lib/jvm/java ALT_BOOTDIR=/usr/lib/jvm/java ANT="/usr/bin/ant" STATIC_CXX="false" NO_DOCS="true" DEBUG_CLASSFILES="true" DEBUG_BINARIES="true" STRIP_POLICY=no_strip HOTSPOT_BUILD_JOBS=8 BUILTIN_SIM=true ARCH=aarch64 debug_build

# ensure hsdis lib is installed
if [ ! -f build/linux-aarch64-normal-server-slowdebug/images/j2sdk-image/jre/lib/aarch64/hsdis-aarch64.so ] ; then
  cp hotspot/src/share/tools/hsdis/build/linux-amd64/hsdis-amd64.so \
     build/linux-aarch64-debug/j2sdk-image/jre/lib/aarch64/hsdis-aarch64.so
fi
